# Generated by Django 5.2 on 2025-04-12 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wpis na blogu', 'verbose_name_plural': 'Wpisy na blogu'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.RemoveField(
            model_name='fishingspot',
            name='posts_app',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='catch',
            name='fishing_method',
            field=models.CharField(choices=[('Feeder', 'Wędkarstwo morskie'), ('Wędkarstwo spławikowe', 'Wędkarstwo muchowe'), ('Wędkarstwo gruntowe', 'Spinning')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='catch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_app', to='posts_app.catch'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts_app.fishspecies'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts_app.fishingspot'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
