# Generated by Django 5.2 on 2025-04-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_alter_post_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catch',
            options={'ordering': ['-date'], 'verbose_name': 'Połów', 'verbose_name_plural': 'Połowy'},
        ),
    ]
