# Generated by Django 5.2 on 2025-04-12 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_alter_catch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='post',
            field=models.ManyToManyField(related_name='catches', to='posts_app.post'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts_app.fishspecies'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='catch',
        ),
        migrations.AddField(
            model_name='post',
            name='catch',
            field=models.ManyToManyField(related_name='posts_app', to='posts_app.catch'),
        ),
    ]
