# Generated by Django 5.2 on 2025-04-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_catch_post_alter_catch_species_remove_post_catch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catch',
            old_name='post',
            new_name='posts_app',
        ),
        migrations.RemoveField(
            model_name='post',
            name='catch',
        ),
    ]
