# Generated by Django 5.2 on 2025-04-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_rename_post_catch_posts_remove_post_catch'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='posts_app.catch'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='posts_app',
            field=models.ManyToManyField(related_name='posts_app', to='posts_app.post'),
        ),
    ]
