# Generated by Django 5.2 on 2025-04-12 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0006_post_catches_alter_catch_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
