# Generated by Django 5.2 on 2025-04-12 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0007_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='posts_app',
            field=models.ManyToManyField(blank=True, related_name='posts_app', to='posts_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_app', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='catches',
        ),
        migrations.AddField(
            model_name='post',
            name='catches',
            field=models.ManyToManyField(blank=True, related_name='catches', to='posts_app.catch'),
        ),
    ]
