# Generated by Django 5.2 on 2025-04-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0008_alter_catch_posts_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='posts_app',
            field=models.ManyToManyField(blank=True, related_name='catch_posts', to='posts_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='catches',
            field=models.ManyToManyField(blank=True, related_name='post_catches', to='posts_app.catch'),
        ),
    ]
