# Generated by Django 5.2 on 2025-04-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0009_alter_catch_posts_alter_post_catches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='fishingspot',
            options={'verbose_name': 'Miejsce Połowu', 'verbose_name_plural': 'Miejsca Połowu'},
        ),
        migrations.AlterModelOptions(
            name='fishspecies',
            options={'verbose_name': 'Gatunek Ryby', 'verbose_name_plural': 'Gatunki Ryb'},
        ),
        migrations.RemoveField(
            model_name='catch',
            name='posts_app',
        ),
    ]
