# Generated by Django 5.2 on 2025-05-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0010_alter_comment_options_alter_fishingspot_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catch',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='catch',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts_app.fishspecies'),
            preserve_default=False,
        ),
    ]
