# Generated by Django 5.2 on 2025-05-19 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0012_alter_catch_author_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingspot',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
