# Generated by Django 5.2 on 2025-05-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0014_rename_author_fishingspot_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
