# Generated by Django 5.2 on 2025-05-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0015_rename_author_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catch',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='fishingspot',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
